config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  has_many :article_categories
  has_many :categories, through: :article_categories
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: { case_sensitive: true }, presence: true, length: { minimum: 3, maximum: 25 }
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/concerns/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    / !! = boolean/
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render "new"
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "Article was deleted."
      redirect_to articles_path
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own articles"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render "edit"
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 3)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render "new"
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render "new"
    end
  end

  def destroy
    flash[:notice] = "Logged out"
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def edit
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your profile was successfully updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      /^log in user after signing up automatically/
      flash[:notice] = "Welcome #{@user.username}, you have successfully signed up!"
      redirect_to articles_path
    else
      render "new"
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles have been deleted"
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
        <div class="col-8 mb-2">
            <div class="card text-center shadow mb-3" id="article-card"
                style="background-color:rgba(236, 243, 252, 0.9)">
                <div class="card-header font-italic font-weight-bold" id="card-header">
                    <%if article.user %>
                    by <%= link_to article.user.username, user_path(article.user) %>
                    <%end%>
                    <div class="mt-2">
                        <% if article.categories.any? %>
                        <%= render article.categories%>
                        <%end%>
                    </div>
                </div>
                <div class="card-body" id="card-body">
                    <h5 class="card-title font-weight-bold">
                        <%= link_to article.title, article_path(article), class:"text-success"%>
                    </h5>
                    <p class="card-text"><%=truncate(article.description, length: 100)%></p>
                    <%=link_to 'View', article_path(article), class: "btn btn-outline-success"%>
                    <%if logged_in? && (article.user == current_user || current_user.admin?)%>
                    <%=link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info"%>
                    <%=link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger"%>
                    <% end%>
                </div>
                <div class="card-footer text-muted" id="card-footer">
                    <small>Created <%= time_ago_in_words(article.created_at) %> ago -
                        Edited <%= time_ago_in_words(article.updated_at) %> ago
                    </small>
                </div>
            </div>
        </div>
    </div>
    <%end%>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <%= form_with(model: @article, local: true)  do |f| %>
            <div class="form-group row">
                <%= f.label :title, class:"col-2 col-form-label" %>
                <div class="col-10">
                    <%= f.text_field :title, class: "form-control shadow rounded", placeholder:"Title"%>
                </div>
            </div>
            <div class="form-group row">
                <%= f.label :description, class:"col-2 col-form-label" %>
                <div class="col-10">
                    <%= f.text_area :description, rows:4, class: "form-control shadow rounded", placeholder:"Description"%>
                </div>
            </div>

            <div class="form-group row">
                <%= f.label :category, class:"col-2 col-form-label" %>
                <div class="col-10">
                    <%= f.collection_select :category_ids, Category.all, :id, :name, {prompt: "Select from the list below"},
                 {multiple: true, size: 3, class:"custom-select shadow rounded"}%>
                </div>
            </div>

            <div class="form-group row justify-content-center">
                <%=f.submit class:"btn btn-outline-info mt-3"%>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
    <h2 class="text-center" id="h2">Edit article</h2>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-8">
                <div class="card text-center shadow mb-3" id="article-card">
                    <div class="card-header font-italic" id="card-header">
                        by <%= @article.user.username%>
                    </div>
                    <div class="card-body">
                        <%= render 'form', class: "justify-content-md-center"%>
                    </div>
                    <div class="card-footer text-muted" id="card-footer">
                        <small>Created <%= time_ago_in_words(@article.created_at) %> ago -
                            Edited <%= time_ago_in_words(@article.updated_at) %> ago
                        </small>
                    </div>
                </div>
                <div class="row justify-content-md-center mb-3">
                    <%=link_to '[ Cancel and return to articles listing ]', articles_path, class: "btn btn-warning"%>
                </div>
            </div>
        </div>
    </div>
</div>

<footer id="sticky-footer" class="bg-dark text-white">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to "Home", root_path%></li>
            <li class="breadcrumb-item"><%= link_to "Articles", articles_path%></li>
            <li class="breadcrumb-item active" aria-current="page">Edit: <%="#{@article.title}"%></li>
        </ol>
    </nav>
    <%= render 'layouts/copyright' %>
</footer>

app/views/articles/show.html.erb
<div id="page-content">
    <h2 class="text-center" id="h2">
        <%= @article.title%>
    </h2>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-8">
                <div class="card text-center shadow mb-3" id="article-card">
                    <div class="card-header font-italic" id="card-header">
                        <div class="mb-2"> by <%= @article.user.username%></div>
                        <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                        <div class="mt-2"><% if @article.categories.any? %>
                            <%= render @article.categories%>
                            <%end%>
                        </div>
                    </div>
                    <div class="card-body text-left" id="card-body">
                        <p><%=simple_format(@article.description)%></p>
                    </div>
                    <%if logged_in? && (@article.user == current_user || current_user.admin?)%>
                    <div class="mb-3">
                        <%=link_to 'Edit', edit_article_path(@article), class: "btn btn-info mr-1"%>
                        <%=link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger"%>
                    </div>
                    <% end %>
                    <div class="card-footer text-muted" id="card-footer">
                        <small>Created <%= time_ago_in_words(@article.created_at) %> ago -
                            Edited <%= time_ago_in_words(@article.updated_at) %> ago
                        </small>
                    </div>
                </div>
                <div class="row justify-content-md-center">
                    <%=link_to '[ Cancel and return to articles listing ]', articles_path, class: "btn btn-outline-warning mb-3"%>
                </div>
            </div>
        </div>
    </div>
</div>
<footer id="sticky-footer" class="bg-dark text-white">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to "Home", root_path%></li>
            <li class="breadcrumb-item"><%= link_to "Articles", articles_path%></li>
            <li class="breadcrumb-item active" aria-current="page">Show Article</li>
        </ol>
    </nav>
    <%= render 'layouts/copyright' %>
</footer>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <%= form_with(model: @category, local: true)  do |f| %>
            <div class="form-group row">
                <%= f.label :name, "Category Name", class:"col-3 col-form-label" %>
                <div class="col-7">
                    <%= f.text_field :name, class: "form-control shadow p-3 rounded", placeholder:"Enter a name"%>
                </div>
            </div>
            <div class="form-group row justify-content-center">
                <%=f.submit class:"btn btn-outline-info btn mt-2"%>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/categories/edit.html.erb
<div id="page-content-show-u">
    <h2 class="text-center text-light mt-4">
        Category: <%= @category.name%> edit
    </h2>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-10">
                <div class="card text-center shadow mb-3" id="article-card">
                    <div class=" card-header font-italic p-4" id="card-header"></div>
                    <div class="card-body">
                        <%= render 'form'%>
                    </div>
                    <div class="card-footer text-muted p-4" id="card-footer">
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <%=link_to '[ Return to all categories ]', categories_path, class: "btn btn-info m-3"%>
            <%=link_to '[ Return to homepage ]', root_path, class: "btn btn-warning m-3"%>
        </div>
    </div>
</div>
<footer id="sticky-footer" class="bg-dark text-white">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to "Home", root_path%></li>
            <li class="breadcrumb-item"><%= link_to "Categories", categories_path%></li>
            <li class="breadcrumb-item"><%= link_to  "#{@category.name}", category_path%></li>
            <li class="breadcrumb-item active" aria-current="page">Edit: <%="#{@category.name}"%> </li>
        </ol>
    </nav>
    <%= render 'layouts/copyright' %>
</footer>

app/views/categories/index.html.erb
<div id="page-content">
    <h2 class="text-center" id="h2">Show Categories</h2>
    <div class="container">
        <div class="flickr_pagination">
            <div class="page_info mb-3">
                <%= will_paginate @categories, :container => false %>
            </div>
        </div>
        <% @categories.each do |category| %>
        <div class="row justify-content-md-center">
            <div class="col-4 mb-2">
                <div class="card text-center shadow mb-3" id="article-card"
                    style="background-color:rgba(236, 243, 252, 0.9)">
                    <div class="card-body" id="card-body">
                        <h5 class="card-title font-weight-bold">
                            <%= link_to category.name, category_path(category), class:"text-success"%>
                        </h5>
                        <p class="card-text">
                            <%= pluralize(category.articles.count, "article") %>
                        </p>
                    </div>
                    <div class="card-footer text-muted" id="card-footer">
                        <small>Created <%= time_ago_in_words(category.created_at) %> ago -
                            Edited <%= time_ago_in_words(category.updated_at) %> ago
                        </small>
                    </div>
                </div>
            </div>
        </div>
        <%end%>
    </div>
    <div class="flickr_pagination">
        <div class="page_info mb-3">
            <%= will_paginate @categories, :container => false %>
        </div>
    </div>
</div>
<footer id="sticky-footer" class="bg-dark text-white">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to "Home", root_path%></li>
            <li class="breadcrumb-item active" aria-current="page">Show Categories</li>
        </ol>
    </nav>
    <%= render 'layouts/copyright' %>
</footer>

app/views/categories/show.html.erb
<div id="page-content-show-u">
    <h2 class="text-center text-light mt-4">
        Category: <%= @category.name%>
    </h2>
    <%if logged_in? &&  current_user.admin?%>
    <div class="text-center mb-2">
        <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-success m-2" %>
    </div>
    <%end%>
</div>

<div id="page-content-show_u_articles">
    <h2 class="text-center text-light p-2">
        <div class="mt-3">
            Articles
        </div>
    </h2>
    <div class="flickr_pagination">
        <div class="page_info mb-3">
            <%= will_paginate @articles, :container => false %>
        </div>
    </div>
    <%= render 'articles/article' %>
    <div class="flickr_pagination">
        <div class="page_info mb-2">
            <%= will_paginate @articles , :container => false %>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <%=link_to '[ Return to all categories ]', categories_path, class: "btn btn-info m-3"%>
        <%=link_to '[ Return to homepage ]', root_path, class: "btn btn-warning m-3"%>
    </div>
</div>

<footer id="sticky-footer" class="bg-dark text-white">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to "Home", root_path%></li>
            <li class="breadcrumb-item"><%= link_to "Categories", categories_path%></li>
            <li class="breadcrumb-item active" aria-current="page">Show Category</li>
        </ol>
    </nav>
    <%= render 'layouts/copyright' %>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "LUIS BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <%= link_to "Bloggers", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Articles
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <% if logged_in? %>
                    <%= link_to "Create new article", new_article_path, class:"dropdown-item" %>
                    <%end%>
                    <%= link_to "View articles", articles_path, class:"dropdown-item" %>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <% if logged_in? && current_user.admin? %>
                    <%= link_to "Create new category", new_category_path, class:"dropdown-item" %>
                    <%end%>
                    <%= link_to "View categories", categories_path, class:"dropdown-item" %>
                </div>
            </li>

            <% if logged_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle font-italic" id="navbarDropdown_user" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= "(Admin)" if current_user.admin? %>[<%= current_user.username %>]
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "View your profile", user_path(current_user), class:"dropdown-item" %>
                    <%= link_to "Edit your profile", edit_user_path(current_user), class:"dropdown-item" %>
                    <%= link_to "Delete profile", user_path(current_user), class:"dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                </div>
            </li>
            <li class="nav-item">
                <%= link_to 'Logout', logout_path, class: "nav-link font-weight-bold", method: :delete %>
            </li>
            <% else%>
            <li class="nav-item">
                <%= link_to 'Login', login_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to 'Sign up', signup_path, class: "nav-link"%>
            </li>
            <%end%>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

app/views/pages/home.html.erb
<div id="page-content-home">
    <div class="jumbotron text-wrap">
        <div class="row justify-content-ld-center">
            <h1 class="display-3">Hello World!</h1>
        </div>
        <div class="row justify-content-ld-center">
            <div class="row justify-content-md-center">
                <%=link_to 'Sign up', signup_path, id:"sign_up_btn", class: "btn btn-success"%>
            </div>
        </div>
    </div>
</div>
<footer id="sticky-footer" class="bg-dark text-white">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Home</li>
        </ol>
    </nav>
    <%= render 'layouts/copyright' %>
</footer>
</div>

app/views/users/edit.html.erb
<div id="page-content">
    <h2 class="text-center" id="h2">Edit your profile</h2>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-10">
                <div class="card text-center shadow mb-3" id="article-card">
                    <div class=" card-header p-4 mb-3" id="card-header"></div>
                    <div class="card-body-new">
                        <%= render 'form'%>
                    </div>
                    <div class="card-footer p-4" id="card-footer">
                    </div>
                </div>
                <div class="row justify-content-md-center mb-3">
                    <%=link_to '[ Cancel and return to Homepage ]', root_path, class: "btn btn-warning mt-2"%>
                </div>
            </div>
        </div>
    </div>
</div>

<footer id="sticky-footer" class="bg-dark text-white">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to "Home", root_path%></li>
            <li class="breadcrumb-item"><%= link_to "Bloggers", users_path%></li>
            <li class="breadcrumb-item active" aria-current="page">Edit <%="#{@user.username}"%>'s profile</li>
        </ol>
    </nav>
    <%= render 'layouts/copyright' %>
</footer>

app/views/users/index.html.erb
<div id="page-content">
    <h2 class="text-center" id="h2">Bloggers</h2>
    <div class="flickr_pagination">
        <div class="page_info mb-3">
            <%= will_paginate @articles, :container => false %>
        </div>
    </div>
    <div class="container">
        <% @users.each do |user| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mb-3">
                <div class="card text-center shadow mb-3" id="article-card">
                    <div class="card-header font-italic font-weight-bold" id="card-header">
                        <%= link_to user.username, user%>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= link_to gravatar_for(user, size:150), user %>
                        </h5>
                        <p class="card-text text-success font-weight-bold">
                            <%= pluralize(user.articles.count, "article") %>
                        </p>
                        <%=link_to 'View profile', user, class: "btn btn-outline-success"%>
                        <%if logged_in? %>
                        <% if user == current_user%>
                        <%=link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-info"%>
                        <%end%>
                        <% if current_user.admin?%>
                        <%=link_to 'Delete user', user_path(user), class: "btn btn-outline-danger", method: :delete,
                                data: {confirm: "Are you sure you want to delete the user account and all associated articles?"}%>
                        <% end %>
                        <%end%>
                    </div>
                    <div class="card-footer text-muted" id="card-footer">
                        <small>Joined <%= time_ago_in_words(user.created_at) %> ago </small>
                    </div>
                </div>
            </div>
        </div>
        <%end%>
    </div>
    <div class="flickr_pagination">
        <div class="page_info mb-4">
            <%= will_paginate @articles, :container => false %>
        </div>
    </div>
</div>

<footer id="sticky-footer" class="bg-dark text-white">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to "Home", root_path%></li>
            <li class="breadcrumb-item active" aria-current="page">Show Bloggers</li>
        </ol>
    </nav>
    <%= render 'layouts/copyright' %>
</footer>

app/views/users/show.html.erb
<div id="page-content-show-u">
    <h2 class="text-center text-light m-4">
        <%= @user.username%>'s profile
    </h2>
    <div class="container mt-2 mb-3">
        <div class="row justify-content-md-center">
            <div class="col-5 mb-2">
                <div class="card text-center shadow mb-3" id="article-card">
                    <div class="card-header font-italic font-weight-bold" id="card-header">
                        <%= @user.username%>'s profile
                        <div class="card-img-top-left m-4 zoom">
                            <%= gravatar_for @user, size: 130%>
                        </div>
                    </div>

                    <%if logged_in? && @user == current_user%>
                    <div class="text-center">
                        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-success m-2" %>
                    </div>
                    <%end%>
                    <div class="card-body" id="card-body-u">
                        <h5 class="card-title">
                            Your profile info
                        </h5>
                    </div>
                </div>
                <div class="row justify-content-md-center">
                    <%=link_to '[ Return to all bloggers ]', users_path, class: "btn btn-info m-2"%>
                    <%=link_to '[ Return to homepage ]', root_path, class: "btn btn-warning m-2"%>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="page-content-show_u_articles">
    <h2 class="text-center text-light p-2">
        <div class="mt-3">
            <%= @user.username%>'s articles
        </div>
    </h2>
    <div class="flickr_pagination">
        <div class="page_info mb-3">
            <%= will_paginate @articles, :container => false %>
        </div>
    </div>
    <%= render 'articles/article' %>
    <div class="flickr_pagination">
        <div class="page_info mb-3">
            <%= will_paginate @articles, :container => false %>
        </div>
    </div>
</div>
<footer id="sticky-footer" class="bg-dark text-white">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to "Home", root_path%></li>
            <li class="breadcrumb-item"><%= link_to "Bloggers", users_path%></li>
            <li class="breadcrumb-item active" aria-current="page">Show profile</li>
        </ol>
    </nav>
    <%= render 'layouts/copyright' %>
</footer>